# Generated by Django 4.2.3 on 2025-07-11 11:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user', primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, help_text='Unique username for login', max_length=50, unique=True)),
                ('email', models.CharField(db_index=True, help_text="User's email address", max_length=255, unique=True)),
                ('password_hash', models.CharField(help_text='Hashed password', max_length=255)),
                ('full_name', models.CharField(blank=True, help_text="User's full display name", max_length=255, null=True)),
                ('avatar_url', models.URLField(blank=True, help_text="URL to user's avatar image", max_length=500, null=True)),
                ('address', models.TextField(blank=True, help_text="User's address", null=True)),
                ('interests', models.JSONField(blank=True, default=list, help_text='List of user interests')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Account creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login timestamp', null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, help_text='Hashed token value', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Token creation timestamp')),
                ('expires_at', models.DateTimeField(help_text='Token expiration timestamp')),
                ('is_active', models.BooleanField(default=True, help_text='Whether token is still valid')),
                ('user', models.ForeignKey(help_text='User this token belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='user_manager.user')),
            ],
            options={
                'verbose_name': 'User Token',
                'verbose_name_plural': 'User Tokens',
                'db_table': 'user_tokens',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_profile_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('interests', models.TextField()),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('passport_nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('seat_preference', models.CharField(blank=True, max_length=50, null=True)),
                ('food_preference', models.TextField(blank=True, null=True)),
                ('allergies', models.JSONField(blank=True, default=list, null=True)),
                ('likes', models.JSONField(blank=True, default=list, null=True)),
                ('dislikes', models.JSONField(blank=True, default=list, null=True)),
                ('price_sensitivity', models.JSONField(blank=True, default=list, null=True)),
                ('home_address', models.TextField(blank=True, null=True)),
                ('local_prefer_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_uuid', models.ForeignKey(blank=True, db_column='user_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='user_manager.user')),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['token_hash'], name='user_tokens_token_h_f1ee2a_idx'),
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['user', 'is_active'], name='user_tokens_user_id_f250ab_idx'),
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['expires_at'], name='user_tokens_expires_124baa_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user_uuid'], name='user_profil_user_uu_01ef4b_idx'),
        ),
    ]
