# Generated by Django 4.2.3 on 2025-07-12 05:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_remove_user_avatar_address_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('itinerary', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_uuid', models.ForeignKey(db_column='user_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='user_manager.user')),
            ],
            options={
                'db_table': 'plans',
                'indexes': [models.Index(fields=['user_uuid'], name='plans_user_uu_851447_idx')],
            },
        ),
    ]
