# Generated by Django 4.2.3 on 2025-07-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0003_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='del_flg',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
    ]
