# Generated by Django 4.2.3 on 2025-07-14 12:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0004_plan_del_flg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('lat', models.CharField(max_length=50)),
                ('long', models.CharField(max_length=50)),
                ('review_ratings', models.CharField(max_length=20)),
                ('highlights', models.CharField(max_length=1000)),
                ('image_url', models.CharField(max_length=500)),
                ('map_url', models.CharField(max_length=500)),
                ('place_id', models.CharField(max_length=100)),
                ('del_flg', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_uuid', models.ForeignKey(db_column='user_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='places', to='user_manager.user')),
            ],
            options={
                'db_table': 'places',
                'indexes': [models.Index(fields=['user_uuid'], name='places_user_uu_fae3a3_idx'), models.Index(fields=['place_id'], name='places_place_i_200b9f_idx')],
            },
        ),
    ]
